version: '3'

services:
  db: 
    image: mysql:5.7.44
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: 
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
